"""Vista Charts: analisi automatica, radar, galassia, mesi, simulatore what-if."""

import pandas as pd
import streamlit as st

from src.analytics.insights import generate_insights, monthly_returns
from src.analytics.simulation import simulate_shock
from src.portfolio.returns import per_ticker_cumulative_return
from src.portfolio.risk import correlation_matrix
from src.ui.components import eur, sec
from src.views.common import BENCHMARK
from src.views.context import ViewContext
from src.visualization.charts import (
    galaxy_chart,
    monthly_bars,
    radar_chart,
    weight_vs_risk_bars,
)


def render(ctx: ViewContext) -> None:
    c = ctx.computed
    amounts, total, portfolio = ctx.amounts, ctx.total, ctx.portfolio
    period = ctx.period

    col_ai, col_radar = st.columns([1.3, 1], gap="large")
    with col_ai:
        sec("Automatic analysis")
        insights = generate_insights(
            period,
            c["cum_return"],
            c["contributions"],
            c["avg_corr"],
            c["drawdown"],
            c["beta"],
            BENCHMARK,
        )
        for insight in insights:
            st.markdown(insight)
        st.caption("Generated by deterministic rules on your data, not by a model.")
    with col_radar:
        sec("Risk radar")
        st.altair_chart(radar_chart(c["radar"]), width="stretch")

    col_galaxy, col_timeline = st.columns([1.15, 1], gap="large")
    with col_galaxy:
        sec("Your galaxy")
        st.caption("Size = weight · color = return · proximity = correlation")
        if len(amounts) >= 2:
            corr = correlation_matrix(c["returns"], min_periods=c["min_periods"])
            weights_s = pd.Series({p["ticker"]: p["weight"] for p in portfolio})
            st.altair_chart(
                galaxy_chart(corr, weights_s, per_ticker_cumulative_return(c["prices"])),
                width="stretch",
            )
        else:
            st.info("At least 2 stocks are needed.")
    with col_timeline:
        sec("Month by month")
        monthly = monthly_returns(c["pf_daily"])
        if len(monthly) >= 2:
            st.altair_chart(monthly_bars(monthly), width="stretch")
            best, worst = monthly.idxmax(), monthly.idxmin()
            st.caption(
                f"Best month: **{best.strftime('%b %Y')}** ({monthly.max():+.1%}) "
                f"· worst: **{worst.strftime('%b %Y')}** ({monthly.min():+.1%})"
            )
        else:
            st.info("Period too short for the monthly view.")

    if len(amounts) >= 2:
        col_wr, col_wr_txt = st.columns([1.5, 1], gap="large")
        with col_wr:
            sec("Invested weight vs risk contribution")
            weights_series_ui = pd.Series({p["ticker"]: p["weight"] for p in portfolio})
            st.altair_chart(
                weight_vs_risk_bars(weights_series_ui, c["contributions"]),
                width="stretch",
            )
        with col_wr_txt:
            sec("How to read it")
            top_c = c["contributions"].index[0]
            gap = float(c["contributions"].iloc[0] - weights_series_ui.get(top_c, 0))
            st.markdown(
                f"When the amber bar exceeds the blue one, the stock weighs on "
                f"risk **more than it weighs on capital**. "
                f"Today **{top_c}** drives "
                f"**{c['contributions'].iloc[0]:.0%}** of risk "
                f"({gap:+.0%} versus its weight)."
            )
            st.caption(
                "Marginal contribution to portfolio variance: it accounts for "
                "volatility and correlations, not just the invested amount."
            )

    sec('"What if?" simulator')
    col_sim_in, col_sim_out = st.columns([1, 2], gap="large")
    with col_sim_in:
        sim_ticker = st.selectbox("If this stock...", sorted(amounts))
        shock_pct = st.slider("...moved by", -50, 50, -20, step=5, format="%d%%")
    with col_sim_out:
        impact = simulate_shock(c["returns"], portfolio, sim_ticker, shock_pct / 100)
        s1, s2, s3 = st.columns(3)
        s1.metric("Portfolio today", eur(total))
        s2.metric(
            "After the shock (with contagion)",
            eur(total * (1 + impact["total"])),
            delta=f"{impact['total']:+.1%}",
        )
        s3.metric(
            "Direct effect only",
            eur(total * (1 + impact["direct"])),
            delta=f"{impact['direct']:+.1%}",
            delta_color="off",
        )
        st.caption(
            "Contagion estimates how the other holdings would react, "
            "using their historical betas toward the shocked stock."
        )
