"""initial schema

Revision ID: d383c8047b66
Revises:
Create Date: 2026-10-04 01:48:05.523305

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d383c8047b66"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("advisor", sa.String(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("portfolio", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("invested", sa.Float(), nullable=False),
        sa.Column("cum_return", sa.Float(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analyses_advisor"), "analyses", ["advisor"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("advisor", sa.String(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("detail", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_advisor"), "audit_log", ["advisor"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("advisor", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("positions", sa.Text(), nullable=False),
        sa.Column("updated", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("advisor", "name"),
    )
    op.create_table(
        "prices",
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("date", "ticker"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("prices")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_audit_log_advisor"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_analyses_advisor"), table_name="analyses")
    op.drop_table("analyses")
    # ### end Alembic commands ###
