[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#0f1115"
secondaryBackgroundColor = "#161a22"
textColor = "#e8e8e3"
